# Generated by Django 5.0.6 on 2024-07-27 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productidsequence_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
