# Generated by Django 5.0.6 on 2024-09-27 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_accessoryorder_machineryorder_springorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessoryorder',
            old_name='price_per_unit',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='machineryorder',
            old_name='price_per_unit',
            new_name='price',
        ),
    ]
