# Generated by Django 5.0.6 on 2024-10-01 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_price_per_unit_accessoryorder_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminIDSequence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('current_id', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
