# Generated by Django 5.0.6 on 2024-10-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_adminidsequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoryorder',
            name='status',
            field=models.CharField(default='open', max_length=50),
        ),
        migrations.AddField(
            model_name='machineryorder',
            name='status',
            field=models.CharField(default='open', max_length=50),
        ),
        migrations.AddField(
            model_name='springorder',
            name='status',
            field=models.CharField(default='open', max_length=50),
        ),
    ]
